import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="sticky top-0 bg-neutral-500 h-12 px-4 flex items-center justify-end">
          <span>Frontend Book</span>
        </header>
        <main className="grid grid-cols-[auto_1fr] h-auto">
          <input type="checkbox" className="peer fixed top-5 left-8" />
          <nav className="bg-neutral-300 w-0 px-0 py-4 peer-checked:w-64 peer-checked:px-4 duration-150">
            sidebar
          </nav>
          <article className="bg-neutral-200 p-4">{children}</article>
        </main>
        <footer className="bg-neutral-600 px-4 h-24 flex items-center">
          footer
        </footer>
      </body>
    </html>
  );
}

// TODO: サイドメニュー作成
