import type { ReactNode } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { SideMenu } from "@/components/side-menu";
import { getArticleIndexes } from "@/libs/get-article-indexes";
import "./globals.css";

export const metadata: Metadata = {
  title: { default: "Frontend Book", template: "%s | Frontend Book" },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const articleIndexes = await getArticleIndexes();

  return (
    <html lang="ja">
      <body>
        <header className="sticky top-0 z-10 flex h-16 items-center border-b border-b-neutral-300 px-24 backdrop-blur md:px-10">
          <Link href="/" className="text-xl font-bold">
            Frontend Book
          </Link>
        </header>
        <SideMenu articleIndexes={articleIndexes} />
        <main>
          <article className="prose prose-neutral max-w-none break-all p-10 md:ml-64">
            {children}
          </article>
        </main>
        <footer className="py-10 text-center text-xs">
          &copy; 2024 Frontend Book
        </footer>
      </body>
    </html>
  );
}
